### ISSUE TITLE
xstream版本1.4.8后需要配置安全框架

### ISSUE THREAD

**Issue by nononohurricane** [binarywang/java-emoji-converter#13]
### xstream版本1.4.8后需要配置安全框架

> [com.thoughtworks.xstream.security.ForbiddenClassException](): [com.github.binarywang.java.emoji.model.Emoji4Unicode]()
> 	[at]() [com.thoughtworks.xstream.security.NoTypePermission.allows]()([NoTypePermission.java]():[26]())
> 	[at]() [com.thoughtworks.xstream.mapper.SecurityMapper.realClass]()([SecurityMapper.java]():[74]())
> 	[at]() [com.thoughtworks.xstream.mapper.MapperWrapper.realClass]()([MapperWrapper.java]():[125]())
> 	[at]() [com.thoughtworks.xstream.mapper.CachingMapper.realClass]()([CachingMapper.java]():[47]())
> 	[at]() [com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType]()([HierarchicalStreams.java]():[29]())
> 	[at]() [com.thoughtworks.xstream.core.TreeUnmarshaller.start]()([TreeUnmarshaller.java]():[133]())
> 	[at]() [com.thoughtworks.xstream.core.Abst]()ractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
> 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1391)
> 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1376)
> 	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1327)
> 	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1281)
> 	at com.github.binarywang.java.emoji.EmojiReader.read(EmojiReader.java:53)
> 	at com.github.binarywang.java.emoji.EmojiReader.getSb2UnicodeMap(EmojiReader.java:81)
> 	at com.github.binarywang.java.emoji.EmojiConverter.sb2Unicode(EmojiConverter.java:49)
> 	at com.github.binarywang.java.emoji.EmojiConverter.toAlias(EmojiConverter.java:32)

**Comment by binarywang** [comment]
谢谢提醒

**Comment by binarywang** [comment]
已修复并发布最新版，欢迎试用
