### ISSUE TITLE
表情库不全，怎么更新表情库？

### ISSUE THREAD

**Issue by zhangzhiqiangit** [binarywang/java-emoji-converter#3]
如题，输入一些新的表情，还是不能解析的

**Comment by zhangzhiqiangit** [comment]
感谢感谢

**Comment by binarywang** [comment]
比如呢？

**Comment by binarywang** [comment]
欢迎提供新的表情以及对应关系，我们一起想办法揉进来

**Comment by zhangzhiqiangit** [comment]
比如🤣，倾斜的笑哭表情

**Comment by binarywang** [comment]
我有空考虑一下

**Comment by huansinho** [comment]
@zhangzhiqiangit 是安卓系统吗？这个表情可能是手机系统不支持。部分安卓机型上是可以看到的。
建议用这个地址测试看看 https://emojipedia.org/unicode-9.0/ 第一个就是倾斜的笑哭表情

**Comment by zhangzhiqiangit** [comment]
@huansinho 是ios系统，ios系统有很多表情安卓是看不到的。。。我看微信上也是显示空的

**Comment by huansinho** [comment]
@zhangzhiqiangit  我IOS可以显示这个表情符：emojiConverter.toHtml("🤡🤣💵👺👹🎃🤖👾")

**Comment by cuizhenjie** [comment]
部分字符规则无法识别，比如：🦳

**Comment by binarywang** [comment]
请使用最新版，看是否已支持，再不行的话，请尝试自行升级emoji-java的版本为最新版
