### ISSUE TITLE
部分表情转换不了

### ISSUE THREAD

**Issue by lw201608** [binarywang/java-emoji-converter#6]
比如这两个表情🧠🤮

**Comment by binarywang** [comment]
这些表情哪里来的？

**Comment by lw201608** [comment]
> 这些表情哪里来的？

**Comment by lw201608** [comment]
> 这些表情哪里来的？

切换emoji-java最新解决了
<dependency>
	<groupId>com.vdurmont</groupId>
	<artifactId>emoji-java</artifactId>
	<version>[5.1.1,)</version>
</dependency>
默认3.2.0有点旧了，有些表情还是不支持

**Comment by binarywang** [comment]
1.0.1新版本已发布，可以使用这个版本
